# Python Basic Tutorial 

# Libraries

A library is a collection of modules or a single module. Modules are python programs that can be imported in another Python program. Libraries are the tools we will use to make our program.

Some special libraries such import $TensorFlow, Keras, Geopandas$ requiere of using Conda Promtp. We back this issue later. 


In [1]:
import pandas as pd
import numpy as np

### Python Types

There are three key python types: int, float, string and boolean.

In [2]:
# Int type
a = 30
print(type(a))

# Float type
a2 = 3.1416165516
print(type(a2))

#String type
c1 = "Machine Learning"
c2 = "Causal inference"
type(c1)
print(c1,'\n',c2)
print(c1+" ; " +c2)


<class 'int'>
<class 'float'>
Machine Learning 
 Causal inference
Machine Learning ; Causal inference


In [3]:
# get some strings 

print(c1[0], ";", c2[0:6])

# Use f-string 

print(f'{c1} y {c2} course')

M ; Causal
Machine Learning y Causal inference course


In [4]:
# Boolean variables
a = True
b = False

print(type(a), '\n', type(b))

"a" == "a"

z1 = (10 > 20)

z2 = (1==1)

print(z2,'\n', z1)

int(z1)



<class 'bool'> 
 <class 'bool'>
True 
 False


0

## 3.0 Tuple

#### It is an ordered and immutable Python object

In [38]:
T1 = (1,4,8,10,20,15,4,5,8,8)
type(T1)


print("Suma:", sum(T1),'\n', "Minimo:", min(T1), '\n', "Maximo:", max(T1))

Suma: 83 
 Minimo: 1 
 Maximo: 20


In [42]:
# It is not possible to change
T1[1] = 5

TypeError: 'tuple' object does not support item assignment

# 4.0 List

#### It is an ordered and mutable Python container.

In [6]:
# Empty List

L1 = []

In [231]:
a = [3,4,5,"ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
type(a)

list

In [233]:
a.append('San Miguel')
print(a)

[3, 4, 5, 'ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'San Miguel', 'San Miguel']


### Indexing
Selecting elements starting from 0. I know it sounds crazy. 
Selecting takes one position before the last requested column

In [7]:
print('first element:',a[0])
print(a[1:4]) # takes element position 1° to 3°, NOT 4°
print('first 5 element:',a[0:5]) # 0,1,2,3,4 

first element: 3
[4, 5, 'ATE']
first 5 element: [3, 4, 5, 'ATE', 'BARRANCO']


In [8]:
# use next line to complete list

b = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
            ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [9]:
# last elements 
print(b[-3:])

['COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA']


In [10]:
len(b)

11

In [11]:
# add elements to list

num = [10,20,30]
b.extend(num)
print(b)

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA', 10, 20, 30]


# Dictionaries - THE WITCH
It is a unordered and mutable Python container.

In [12]:
# dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 }
population.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'])

In [13]:
population['Berlin']

3748148

In [14]:
population['Hamburg']

1822445

In [15]:
population_18_19 = {'Berlin': [3748148, 38000, "alex"], 'Hamburg': [1822445, 1922445], 
                    'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056 , 'lima': 1100000}

In [16]:
population_18_19['Berlin']

[3748148, 38000, 'alex']

In [17]:
pop_germnay = population_18_19["Berlin"][0] + population_18_19["Munich"] + population_18_19["Hamburg"][0]+ population_18_19["Frankfurt"]
pop_germnay

7795157

In [18]:
Postal_code =  {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : {"Upper_bound":"18.2%", "Lower_bound":"14.4%"}, "Population" : "20 mil"}}

Postal_code

{'LOMAS': {'UBIGEO': 40311,
  'Poverty Rate': {'Upper_bound': '18.2%', 'Lower_bound': '14.4%'},
  'Population': '20 mil'}}

In [19]:
Postal_code['LOMAS']['Poverty Rate']

{'Upper_bound': '18.2%', 'Lower_bound': '14.4%'}

In [20]:
Postal_code['LOMAS']['Poverty Rate']['Upper_bound']

'18.2%'

# Array (vectors and matrix)

### [Key Methods](https://cs231n.github.io/python-numpy-tutorial/)

| Method | Description |
| -------- | ------------ |
|dtype  | type of elements in the array|
|ndim   |  dimension of array|
|shape  |  tuple with the dimmension of the array|
|size |  total number of elements in the array|

In [21]:
a = np.array( [1, 2, 3, 4, 5] )
a
type(a)

numpy.ndarray

In [22]:
print(a.size)
print(a.shape)
print(a.ndim)

5
(5,)
1


In [23]:
# 2D array
M = np.array( [ [3, 4, 2], [1, 2, 6] ] )
print(M)
print("n° elements:", M.size, '\n', "rows and columns:", M.shape, '\n', "n° dimension:", M.ndim)

[[3 4 2]
 [1 2 6]]
n° elements: 6 
 rows and columns: (2, 3) 
 n° dimension: 2


### ***[Array Creation Routines](https://numpy.org/doc/stable/reference/routines.array-creation.html)***


|Function|Return|
| --- | --- |
|arange( )|array of sequence|
|eye( )|diagonal array|
|ones( )|array of ones|
|zeros( )|array of zeros|

In [24]:
peru = np.arange(start = 1,stop = 13,step = 5)
print(peru)
type(peru)

[ 1  6 11]


numpy.ndarray

In [25]:
y = np.arange( 0, 20, 2 )
print(y)
print(y[0:3])

[ 0  2  4  6  8 10 12 14 16 18]
[0 2 4]


In [26]:
y1 = np.arange( 1, 10 ) # one step 

In [27]:
a4 = np.ones(10)
print(a4, '\n')
a5 = np.ones((10,10))
print(a5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
a6 = np.zeros(5)
print(a6,'\n')
a7 = np.zeros((10,10))
print(a7)

[0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [29]:
a8 = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])
a8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [30]:
a8[2:5,:]  # rows selecrtion

array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [31]:
a8[:,0:6]  # columns selecrtion

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

### ***[Array Manipulation](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)***

In [32]:
# Reshape

w = np.arange(0,24)
print( w )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [33]:
print(w.reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [34]:
print(w.reshape(2,12))

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [35]:
M1 = np.zeros( (8, 2) )
M2 = np.ones( (8, 4) )
print(M1,"\n","\n", M2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
M3 = np.hstack((M1,M2))  # add columns in horizontal way
M3

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

## Axis

### axis = 0 : vertical operation
### axis = 1 : horizontal operation

In [37]:
con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [38]:
# Transpose
mat_3 = M3.T
print("mat5 \n" , mat_3)

mat5 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [40]:
M5 = np.vstack((M3,M4))  # add columns in horizontal way
M5

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [41]:
con2 = np.concatenate((M3,M4), axis = 0) # add more rows. This is a vertical operation
con2

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [2., 2., 3., 4., 5., 1.],
       [1., 5., 5., 9., 8., 2.]])

In [42]:

mat_5 = M5.T
print("mat4 \n" , mat_5)

mat4 
 [[0. 0. 0. 0. 0. 0. 0. 0. 2. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 3. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 4. 9.]
 [1. 1. 1. 1. 1. 1. 1. 1. 5. 8.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]]


# [Pandas](https://pandas.pydata.org/docs/user_guide/index.html)
It helps us to store data in a 2-dimensional labeled data structure with columns of potentially different types.

In [43]:
# crear lists
students = ["Alejandro","Pedro","Ramiro","Axel","Juan"]
math = [15,16,10,12,13]
english = [13,9,16,14,17]
art = [12,16,15,19,10]

# Make a dictionary
grades = {"Students": students, "Math":math, "English":english, "Art":art}
grades

{'Students': ['Alejandro', 'Pedro', 'Ramiro', 'Axel', 'Juan'],
 'Math': [15, 16, 10, 12, 13],
 'English': [13, 9, 16, 14, 17],
 'Art': [12, 16, 15, 19, 10]}

In [44]:
data1 = pd.DataFrame(grades)
data1

Students  Math  English  Art
0  Alejandro    15       13   12
1      Pedro    16        9   16
2     Ramiro    10       16   15
3       Axel    12       14   19
4       Juan    13       17   10

In [45]:
# Change columns names
dic1 = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'} # dictionary
data1.rename( columns = dic1)

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [46]:
data1.rename( columns = { "Students":'St', "Math":'Ma', "English":'En', "Art":'Ar'}  )

St  Ma  En  Ar
0  Alejandro  15  13  12
1      Pedro  16   9  16
2     Ramiro  10  16  15
3       Axel  12  14  19
4       Juan  13  17  10

In [47]:
# Add column and index row name
data = {'state': ['Lima', 'Piura', 'Tumbes', 'Cuzco', 'Ica', 'Puno'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [48]:
frame = pd.DataFrame(data, 
                      columns=["year", 'state', 'pop', 'debt'] ,
                      index=['one', 'two', 'three', 'four','five', 'six'] )

frame

year   state  pop debt
one    2000    Lima  1.5  NaN
two    2001   Piura  1.7  NaN
three  2002  Tumbes  3.6  NaN
four   2001   Cuzco  2.4  NaN
five   2002     Ica  2.9  NaN
six    2003    Puno  3.2  NaN

# Load  files : CSV, Excel

In [57]:
#using relative path

base0 = pd.read_excel(r'..\data\base1.xlsx', sheet_name = "data")

print(type(base0))
base0.head()

<class 'pandas.core.frame.DataFrame'>


Unnamed: 0       wage     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  we  \
0          10   9.615385  2.263364    1    0    0    0    1   0   0  ...   0   
1          12  48.076923  3.872802    0    0    0    0    1   0   0  ...   0   
2          15  11.057692  2.403126    0    0    1    0    0   0   0  ...   0   
3          18  13.942308  2.634928    1    0    0    0    0   1   0  ...   0   
4          19  28.846154  3.361977    1    0    0    0    1   0   0  ...   0   

   ne  exp1  exp2    exp3     exp4   occ  occ2   ind  ind2  
0   1   7.0  0.49   0.343   0.2401  3600    11  8370    18  
1   1  31.0  9.61  29.791  92.3521  3050    10  5070     9  
2   1  18.0  3.24   5.832  10.4976  6260    19   770     4  
3   1  25.0  6.25  15.625  39.0625   420     1  6990    12  
4   1  22.0  4.84  10.648  23.4256  2015     6  9470    22  

[5 rows x 21 columns]

In [100]:
#import chardet

#base1 = open(r'../data/base0.csv', 'rb').read()
#det = chardet.detect(base1)
#charenc = det['encoding']
#print(charenc)

base1 = pd.read_csv( r'../data/base0.csv')
base1

Unnamed: 0       wage     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  \
0             10   9.615385  2.263364    1    0    0    0    1   0   0  ...   
1             12  48.076923  3.872802    0    0    0    0    1   0   0  ...   
2             15  11.057692  2.403126    0    0    1    0    0   0   0  ...   
3             18  13.942308  2.634928    1    0    0    0    0   1   0  ...   
4             19  28.846154  3.361977    1    0    0    0    1   0   0  ...   
...          ...        ...       ...  ...  ...  ...  ...  ...  ..  ..  ...   
5145       32620  14.769231  2.692546    0    0    0    0    1   0   0  ...   
5146       32624  23.076923  3.138833    1    0    0    1    0   0   0  ...   
5147       32626  38.461538  3.649659    0    0    0    0    0   1   0  ...   
5148       32631  32.967033  3.495508    0    0    1    0    0   0   0  ...   
5149       32643  17.307692  2.851151    0    0    0    0    0   1   0  ...   

      we  ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0      0   1   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1      0   1  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2      0   1  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3      0   1  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4      0   1  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  
...   ..  ..   ...   ...     ...      ...     ...   ...     ...   ...  
5145   1   0   9.0  0.81   0.729   0.6561  4700.0    16  4970.0     9  
5146   1   0  12.0  1.44   1.728   2.0736  4110.0    13  8680.0    20  
5147   1   0  11.0  1.21   1.331   1.4641  1550.0     4  3680.0     6  
5148   1   0  10.0  1.00   1.000   1.0000  2920.0     9  6570.0    11  
5149   1   0  14.0  1.96   2.744   3.8416  1610.0     5  7460.0    14  

[5150 rows x 21 columns]

In [101]:
base1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5150 entries, 0 to 5149
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  5150 non-null   int64  
 1   wage        5150 non-null   float64
 2   lwage       5150 non-null   float64
 3   sex         5150 non-null   int64  
 4   shs         5150 non-null   int64  
 5   hsg         5150 non-null   int64  
 6   scl         5150 non-null   int64  
 7   clg         5150 non-null   int64  
 8   ad          5150 non-null   int64  
 9   mw          5150 non-null   int64  
 10  so          5150 non-null   int64  
 11  we          5150 non-null   int64  
 12  ne          5150 non-null   int64  
 13  exp1        5150 non-null   float64
 14  exp2        5150 non-null   float64
 15  exp3        5150 non-null   float64
 16  exp4        5150 non-null   float64
 17  occ         5150 non-null   float64
 18  occ2        5150 non-null   int64  
 19  ind         5150 non-null  

In [102]:
base1 = base1.rename( columns = { "wage":'salario', "Unnamed: 0":'id'}  )
base1

id    salario     lwage  sex  shs  hsg  scl  clg  ad  mw  ...  we  \
0        10   9.615385  2.263364    1    0    0    0    1   0   0  ...   0   
1        12  48.076923  3.872802    0    0    0    0    1   0   0  ...   0   
2        15  11.057692  2.403126    0    0    1    0    0   0   0  ...   0   
3        18  13.942308  2.634928    1    0    0    0    0   1   0  ...   0   
4        19  28.846154  3.361977    1    0    0    0    1   0   0  ...   0   
...     ...        ...       ...  ...  ...  ...  ...  ...  ..  ..  ...  ..   
5145  32620  14.769231  2.692546    0    0    0    0    1   0   0  ...   1   
5146  32624  23.076923  3.138833    1    0    0    1    0   0   0  ...   1   
5147  32626  38.461538  3.649659    0    0    0    0    0   1   0  ...   1   
5148  32631  32.967033  3.495508    0    0    1    0    0   0   0  ...   1   
5149  32643  17.307692  2.851151    0    0    0    0    0   1   0  ...   1   

      ne  exp1  exp2    exp3     exp4     occ  occ2     ind  ind2  
0      1   7.0  0.49   0.343   0.2401  3600.0    11  8370.0    18  
1      1  31.0  9.61  29.791  92.3521  3050.0    10  5070.0     9  
2      1  18.0  3.24   5.832  10.4976  6260.0    19   770.0     4  
3      1  25.0  6.25  15.625  39.0625   420.0     1  6990.0    12  
4      1  22.0  4.84  10.648  23.4256  2015.0     6  9470.0    22  
...   ..   ...   ...     ...      ...     ...   ...     ...   ...  
5145   0   9.0  0.81   0.729   0.6561  4700.0    16  4970.0     9  
5146   0  12.0  1.44   1.728   2.0736  4110.0    13  8680.0    20  
5147   0  11.0  1.21   1.331   1.4641  1550.0     4  3680.0     6  
5148   0  10.0  1.00   1.000   1.0000  2920.0     9  6570.0    11  
5149   0  14.0  1.96   2.744   3.8416  1610.0     5  7460.0    14  

[5150 rows x 21 columns]

In [103]:
base1 = base1.drop(["id","ind2"], axis=1)
base1


salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  
0     0.49   0.343   0.2401  3600.0    11  8370.0  
1     9.61  29.791  92.3521  3050.0    10  5070.0  
2     3.24   5.832  10.4976  6260.0    19   770.0  
3     6.25  15.625  39.0625   420.0     1  6990.0  
4     4.84  10.648  23.4256  2015.0     6  9470.0  
...    ...     ...      ...     ...   ...     ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0  
5146  1.44   1.728   2.0736  4110.0    13  8680.0  
5147  1.21   1.331   1.4641  1550.0     4  3680.0  
5148  1.00   1.000   1.0000  2920.0     9  6570.0  
5149  1.96   2.744   3.8416  1610.0     5  7460.0  

[5150 rows x 19 columns]

In [104]:
base1.drop([1,3], axis=0)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5     11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6     19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

       exp2    exp3      exp4     occ  occ2     ind  
0      0.49   0.343    0.2401  3600.0    11  8370.0  
2      3.24   5.832   10.4976  6260.0    19   770.0  
4      4.84  10.648   23.4256  2015.0     6  9470.0  
5      0.01   0.001    0.0001  1650.0     5  7460.0  
6     17.64  74.088  311.1696  5120.0    17  7280.0  
...     ...     ...       ...     ...   ...     ...  
5145   0.81   0.729    0.6561  4700.0    16  4970.0  
5146   1.44   1.728    2.0736  4110.0    13  8680.0  
5147   1.21   1.331    1.4641  1550.0     4  3680.0  
5148   1.00   1.000    1.0000  2920.0     9  6570.0  
5149   1.96   2.744    3.8416  1610.0     5  7460.0  

[5148 rows x 19 columns]

## Slicing  dataframe 

In [114]:
#select rows using positions

base1.iloc[0:10]

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0   9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1  48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2  11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3  13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4  28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5  11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6  19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
7  19.230769  2.956512    0    0    1    0    0   0   0   0   0   1  37.0   
8  12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
9  19.230769  2.956512    1    0    0    0    1   0   0   0   0   1   4.0   

    exp2    exp3      exp4     occ  occ2     ind  
0   0.49   0.343    0.2401  3600.0    11  8370.0  
1   9.61  29.791   92.3521  3050.0    10  5070.0  
2   3.24   5.832   10.4976  6260.0    19   770.0  
3   6.25  15.625   39.0625   420.0     1  6990.0  
4   4.84  10.648   23.4256  2015.0     6  9470.0  
5   0.01   0.001    0.0001  1650.0     5  7460.0  
6  17.64  74.088  311.1696  5120.0    17  7280.0  
7  13.69  50.653  187.4161  5240.0    17  5680.0  
8   9.61  29.791   92.3521  4040.0    13  8590.0  
9   0.16   0.064    0.0256  3255.0    10  8190.0

In [127]:
# select columns using positions

base1.iloc[:,0:5]

salario     lwage  sex  shs  hsg
0      9.615385  2.263364    1    0    0
1     48.076923  3.872802    0    0    0
2     11.057692  2.403126    0    0    1
3     13.942308  2.634928    1    0    0
4     28.846154  3.361977    1    0    0
...         ...       ...  ...  ...  ...
5145  14.769231  2.692546    0    0    0
5146  23.076923  3.138833    1    0    0
5147  38.461538  3.649659    0    0    0
5148  32.967033  3.495508    0    0    1
5149  17.307692  2.851151    0    0    0

[5150 rows x 5 columns]

In [144]:
# row index and columns names 

base1.loc[0:10,['salario', 'lwage']]

salario     lwage
0    9.615385  2.263364
1   48.076923  3.872802
2   11.057692  2.403126
3   13.942308  2.634928
4   28.846154  3.361977
5   11.730769  2.462215
6   19.230769  2.956512
7   19.230769  2.956512
8   12.000000  2.484907
9   19.230769  2.956512
10  17.307692  2.851151

In [140]:
frame.loc[['one','two']]

year  state  pop debt
one  2000   Lima  1.5    1
two  2001  Piura  1.7  NaN

In [150]:
base1[base1['sex']==1].head(10)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0    9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
3   13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4   28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5   11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6   19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
8   12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
9   19.230769  2.956512    1    0    0    0    1   0   0   0   0   1   4.0   
10  17.307692  2.851151    1    0    1    0    0   0   0   0   0   1   7.0   
12  12.019231  2.486508    1    0    0    1    0   0   0   0   0   1   5.5   
13  13.461538  2.599837    1    0    0    1    0   0   0   0   0   1  20.5   

       exp2       exp3        exp4     occ  occ2     ind  
0    0.4900   0.343000    0.240100  3600.0    11  8370.0  
3    6.2500  15.625000   39.062500   420.0     1  6990.0  
4    4.8400  10.648000   23.425600  2015.0     6  9470.0  
5    0.0100   0.001000    0.000100  1650.0     5  7460.0  
6   17.6400  74.088000  311.169600  5120.0    17  7280.0  
8    9.6100  29.791000   92.352100  4040.0    13  8590.0  
9    0.1600   0.064000    0.025600  3255.0    10  8190.0  
10   0.4900   0.343000    0.240100  4020.0    13  8270.0  
12   0.3025   0.166375    0.091506  3600.0    11  8270.0  
13   4.2025   8.615125   17.661006  3645.0    11  8190.0

In [152]:
base1[base.exp1 > 10].head(10)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
1   48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2   11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3   13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4   28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
6   19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
7   19.230769  2.956512    0    0    1    0    0   0   0   0   0   1  37.0   
8   12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
11  12.019231  2.486508    0    0    1    0    0   0   0   0   0   1  30.0   
13  13.461538  2.599837    1    0    0    1    0   0   0   0   0   1  20.5   
14  16.346154  2.793993    1    0    0    0    1   0   0   0   0   1  25.0   

       exp2       exp3        exp4     occ  occ2     ind  
1    9.6100  29.791000   92.352100  3050.0    10  5070.0  
2    3.2400   5.832000   10.497600  6260.0    19   770.0  
3    6.2500  15.625000   39.062500   420.0     1  6990.0  
4    4.8400  10.648000   23.425600  2015.0     6  9470.0  
6   17.6400  74.088000  311.169600  5120.0    17  7280.0  
7   13.6900  50.653000  187.416100  5240.0    17  5680.0  
8    9.6100  29.791000   92.352100  4040.0    13  8590.0  
11   9.0000  27.000000   81.000000  4220.0    14  8270.0  
13   4.2025   8.615125   17.661006  3645.0    11  8190.0  
14   6.2500  15.625000   39.062500   110.0     1  7870.0

In [154]:
base1[(base1['sex']==1) & (base1.exp1 > 10) ].head(10)
base1[(base1['sex']==1) | (base1.exp1 > 10) ].head(10)

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0   9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1  48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2  11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3  13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4  28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
5  11.730769  2.462215    1    0    0    0    1   0   0   0   0   1   1.0   
6  19.230769  2.956512    1    0    1    0    0   0   0   0   0   1  42.0   
7  19.230769  2.956512    0    0    1    0    0   0   0   0   0   1  37.0   
8  12.000000  2.484907    1    0    1    0    0   0   0   0   0   1  31.0   
9  19.230769  2.956512    1    0    0    0    1   0   0   0   0   1   4.0   

    exp2    exp3      exp4     occ  occ2     ind  
0   0.49   0.343    0.2401  3600.0    11  8370.0  
1   9.61  29.791   92.3521  3050.0    10  5070.0  
2   3.24   5.832   10.4976  6260.0    19   770.0  
3   6.25  15.625   39.0625   420.0     1  6990.0  
4   4.84  10.648   23.4256  2015.0     6  9470.0  
5   0.01   0.001    0.0001  1650.0     5  7460.0  
6  17.64  74.088  311.1696  5120.0    17  7280.0  
7  13.69  50.653  187.4161  5240.0    17  5680.0  
8   9.61  29.791   92.3521  4040.0    13  8590.0  
9   0.16   0.064    0.0256  3255.0    10  8190.0

In [159]:
base1.sort_values(["exp1","salario"]).head(20)
base1['dummy'] = np.nan # nan values
base1 

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  dummy  
0     0.49   0.343   0.2401  3600.0    11  8370.0    NaN  
1     9.61  29.791  92.3521  3050.0    10  5070.0    NaN  
2     3.24   5.832  10.4976  6260.0    19   770.0    NaN  
3     6.25  15.625  39.0625   420.0     1  6990.0    NaN  
4     4.84  10.648  23.4256  2015.0     6  9470.0    NaN  
...    ...     ...      ...     ...   ...     ...    ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0    NaN  
5146  1.44   1.728   2.0736  4110.0    13  8680.0    NaN  
5147  1.21   1.331   1.4641  1550.0     4  3680.0    NaN  
5148  1.00   1.000   1.0000  2920.0     9  6570.0    NaN  
5149  1.96   2.744   3.8416  1610.0     5  7460.0    NaN  

[5150 rows x 20 columns]

In [166]:
base1.loc[base1['exp1'] > 10, "dummy"] = 1
base1

salario     lwage  sex  shs  hsg  scl  clg  ad  mw  so  we  ne  exp1  \
0      9.615385  2.263364    1    0    0    0    1   0   0   0   0   1   7.0   
1     48.076923  3.872802    0    0    0    0    1   0   0   0   0   1  31.0   
2     11.057692  2.403126    0    0    1    0    0   0   0   0   0   1  18.0   
3     13.942308  2.634928    1    0    0    0    0   1   0   0   0   1  25.0   
4     28.846154  3.361977    1    0    0    0    1   0   0   0   0   1  22.0   
...         ...       ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..   ...   
5145  14.769231  2.692546    0    0    0    0    1   0   0   0   1   0   9.0   
5146  23.076923  3.138833    1    0    0    1    0   0   0   0   1   0  12.0   
5147  38.461538  3.649659    0    0    0    0    0   1   0   0   1   0  11.0   
5148  32.967033  3.495508    0    0    1    0    0   0   0   0   1   0  10.0   
5149  17.307692  2.851151    0    0    0    0    0   1   0   0   1   0  14.0   

      exp2    exp3     exp4     occ  occ2     ind  dummy  
0     0.49   0.343   0.2401  3600.0    11  8370.0    NaN  
1     9.61  29.791  92.3521  3050.0    10  5070.0    1.0  
2     3.24   5.832  10.4976  6260.0    19   770.0    1.0  
3     6.25  15.625  39.0625   420.0     1  6990.0    1.0  
4     4.84  10.648  23.4256  2015.0     6  9470.0    1.0  
...    ...     ...      ...     ...   ...     ...    ...  
5145  0.81   0.729   0.6561  4700.0    16  4970.0    NaN  
5146  1.44   1.728   2.0736  4110.0    13  8680.0    1.0  
5147  1.21   1.331   1.4641  1550.0     4  3680.0    1.0  
5148  1.00   1.000   1.0000  2920.0     9  6570.0    NaN  
5149  1.96   2.744   3.8416  1610.0     5  7460.0    1.0  

[5150 rows x 20 columns]

# If condition

Function **if** test conditions. 
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

<img src="https://www.dropbox.com/s/8xwqk2ze1116qvp/if-statement.jpg?dl=1" alt="image info" />

In [170]:
A = 20
B = 30

if A == B:
    print( 'Test expresion 1 is True' )
    
elif A > B:
    print( 'Test expresion 2 is True' )

elif A >= B:
    print( 'Test expresion 3 is True' )
    
elif A < B:
    print( 'Test expresion 4 is True' )
    
elif A <= B:
    print( 'Test expresion 5 is True' )
    
else:
    print( 'Test expresion 6 is True' )

Test expresion 4 is True


# For Loops

A for loop is used for iterating over a sequence. It has the following structure:

<img src="https://www.dropbox.com/s/a51fbr4m0vpvobe/for_loop.jpg?dl=1" alt="image info" />



In [173]:
secuencia = np.arange(1,20)

for i in secuencia:
    print("numero",i)

numero 1
numero 2
numero 3
numero 4
numero 5
numero 6
numero 7
numero 8
numero 9
numero 10
numero 11
numero 12
numero 13
numero 14
numero 15
numero 16
numero 17
numero 18
numero 19


In [229]:
born = [ 1980 , 1990 , 2010 , 2008 , 2005, 1999]
years = [2023 , 2021 , 2022 , 2026 , 2027, 2028 ]
age_finish = []

print(len(age),'\n')

for i in np.arange(0,len(age)):
        new = years[ i ] - born[ i ] 
        age_finish.append( new )

age_finish

5 



[43, 31, 12, 18, 22]

In [177]:
# secuencia
students = [ 'Miguel' , 'Anthony', 'Paul', 'Rodrigo', 'Jason' ]

# age
gr_age = [ 20, 18, 15, 20, 22]

semester = [ "2018-1", "2018-2", "2019-1", "2019-2","2020-1"]

# Loops
for student, age, sem in zip( students , gr_age , semester):
    print(f'{ student } is { age }, semester {sem}')

Miguel is 20, semester 2018-1
Anthony is 18, semester 2018-2
Paul is 15, semester 2019-1
Rodrigo is 20, semester 2019-2
Jason is 22, semester 2020-1


# Nested For Loop

In [178]:
age_class = [ [11, 12, 11] , [15, 16, 16] , [17, 17, 18]]

for classs in age_class:
    print( classs )
    
    for age in classs:
        print( age )

[11, 12, 11]
11
12
11
[15, 16, 16]
15
16
16
[17, 17, 18]
17
17
18


# Functions

- `Arguments` − Elements that the function will use to make operations. Arguments are optional and can have default values.

- `Function Body` − This defines what your function does.
- `return` − Specifies the variable that will be the output of the function.

Return Value − The return value of a function is the last expression in the function body to be evaluated.
<br><br>
<font size="4">
<font color='green'>def</font> function_name <font color='green'>(arg_1, arg_2, ...) </font>:<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;Function body <br>
    <br> &nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> result<br>
</font>

In [179]:
def suma(x, y):
    mate = (x + y)*15
    return mate

In [181]:
suma(10,4)

210

In [183]:
def select(B, row, column):

    B = B.iloc[0:row,0:column]
    
    return B

In [184]:
select(base1, 10, 5)

salario     lwage  sex  shs  hsg
0   9.615385  2.263364    1    0    0
1  48.076923  3.872802    0    0    0
2  11.057692  2.403126    0    0    1
3  13.942308  2.634928    1    0    0
4  28.846154  3.361977    1    0    0
5  11.730769  2.462215    1    0    0
6  19.230769  2.956512    1    0    1
7  19.230769  2.956512    0    0    1
8  12.000000  2.484907    1    0    1
9  19.230769  2.956512    1    0    0

In [192]:
notas = np.array( [11, 12, 13, 14, 15, 16, 17, 17, 18])
notas = notas.reshape(9, 1)

In [194]:
def igual_filas_columnas( a):
    
    filas = a.shape[0]
    columnas = a.shape[1]
    comparacion = filas == columnas
    
    return (comparacion)

In [195]:
igual_filas_columnas(notas)

False

# Linear Regression Model

In [234]:
## loading the data
Penn = pd.read_csv("../data/penn_jae.dat" , sep='\s', engine='python')

In [238]:
Penn.shape

(13913, 24)

In [242]:
Penn = Penn[Penn.tg.isin([0,4])]

Penn
 #subset(Penn, tg==4 | tg==0)


abdt  tg  inuidur1  inuidur2  female  black  hispanic  othrace  dep  \
0      10824   0        18        18       0      0         0        0    2   
3      10824   0         1         1       0      0         0        0    0   
4      10747   0        27        27       0      0         0        0    0   
11     10607   4         9         9       0      0         0        0    0   
12     10831   0        27        27       0      0         0        0    1   
...      ...  ..       ...       ...     ...    ...       ...      ...  ...   
13904  10628   4        10        10       0      0         1        0    0   
13905  10523   4         4         4       0      0         1        0    2   
13906  10558   0         9         9       0      0         0        0    2   
13910  10817   4         4         4       0      0         0        0    0   
13911  10691   0        27        27       0      0         0        0    0   

       q1  ...  q5  q6  recall  agelt35  agegt54  durable  nondurable  lusd  \
0       0  ...   0   0       0        0        0        0           0     1   
3       0  ...   0   0       0        0        0        0           1     0   
4       0  ...   0   0       0        0        0        0           1     0   
11      0  ...   0   0       1        0        0        0           0     0   
12      0  ...   0   0       0        1        1        0           1     0   
...    ..  ...  ..  ..     ...      ...      ...      ...         ...   ...   
13904   0  ...   0   0       1        0        0        0           0     0   
13905   0  ...   0   0       0        0        0        0           0     0   
13906   0  ...   0   0       1        0        0        0           1     0   
13910   0  ...   0   0       0        1        0        0           0     0   
13911   0  ...   0   0       0        1        1        0           1     0   

       husd  muld  
0         0   NaN  
3         0   NaN  
4         0   NaN  
11        1   NaN  
12        0   NaN  
...     ...   ...  
13904     1   NaN  
13905     1   NaN  
13906     0   NaN  
13910     0   NaN  
13911     0   NaN  

[5099 rows x 24 columns]

In [273]:
Penn = Penn.replace({"tg":4}, 1)  # replace 4 to 1 
Penn = Penn.rename(columns = {"tg": "T4"})

In [261]:

import statsmodels.formula.api as smf

In [283]:
# Formula regression
formula1 = "T4 ~ female" 

formula2 = "T4 ~ female + black"

# We include only the interaction

formula3 = "T4 ~ female + black + female:black"

# We include the two terms and their interaction

formula4 = "T4 ~ female*black"

# drop intercep

formula5 = "T4 ~ -1 + female + black + female:black"

# polinomial independent varibles

formula6 = "T4 ~ -1 + female + black + female:black + lusd + lusd^2 "

# interaction effects & categorical variables 

formula7 = "T4~(female+black+othrace+C(dep)+q2+q3+q4+q5+q6+agelt35+agegt54+durable+lusd+husd)**2"

In [255]:
# Create category variable
Penn['dep'] = Penn['dep'].astype( 'category' )


In [259]:
Penn['dep'].dtype

CategoricalDtype(categories=[0, 1, 2], ordered=False)

In [288]:
mod = smf.ols(formula1, data=Penn).fit()
print(mod.summary())

                            OLS Regression Results                            
Dep. Variable:                     T4   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                   0.05733
Date:                Tue, 22 Mar 2022   Prob (F-statistic):              0.811
Time:                        15:17:44   Log-Likelihood:                -3433.4
No. Observations:                5099   AIC:                             6871.
Df Residuals:                    5097   BIC:                             6884.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.3435      0.009     39.908      0.0

In [290]:
mod = smf.ols(formula3, data=Penn).fit()

print(mod.summary())

                            OLS Regression Results                            
Dep. Variable:                     T4   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.7254
Date:                Tue, 22 Mar 2022   Prob (F-statistic):              0.537
Time:                        15:18:12   Log-Likelihood:                -3432.3
No. Observations:                5099   AIC:                             6873.
Df Residuals:                    5095   BIC:                             6899.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.3460      0.009     37.761   

In [293]:
mod = smf.ols(formula4, data=Penn).fit()
print(mod.summary())

                            OLS Regression Results                            
Dep. Variable:                     T4   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.7254
Date:                Tue, 22 Mar 2022   Prob (F-statistic):              0.537
Time:                        15:18:44   Log-Likelihood:                -3432.3
No. Observations:                5099   AIC:                             6873.
Df Residuals:                    5095   BIC:                             6899.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.3460      0.009     37.761   

In [292]:
mod = smf.ols(formula6, data=Penn).fit()
print(mod.summary())

                            OLS Regression Results                            
Dep. Variable:                     T4   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.6657
Date:                Tue, 22 Mar 2022   Prob (F-statistic):              0.616
Time:                        15:18:36   Log-Likelihood:                -3432.1
No. Observations:                5099   AIC:                             6874.
Df Residuals:                    5094   BIC:                             6907.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
female          -0.0103      0.014     -0.709   

In [296]:
mod = smf.ols(formula7, data=Penn).fit()
print(mod.summary())


                            OLS Regression Results                            
Dep. Variable:                     T4   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     1.324
Date:                Tue, 22 Mar 2022   Prob (F-statistic):             0.0143
Time:                        15:19:23   Log-Likelihood:                -3360.7
No. Observations:                5099   AIC:                             6941.
Df Residuals:                    4989   BIC:                             7660.
Df Model:                         109                                         
Covariance Type:            nonrobust                                         
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.3890    

In [332]:
Penn = Penn[['female', 'black', 'lusd' , 'dep', 'T4']]

formula_modelB = "T4 ~  female + black + lusd + lusd^2+ C(dep)"

In [333]:
mod = smf.ols(formula_modelB, data = Penn).fit()

print("Parameters: ", mod.params,'\n')

print("R2:", mod.rsquared,'\n')

print("Standard error:", mod.bse,'\n')

print("Predictived values:", mod.predict())

Parameters:  Intercept      0.119043
C(dep)[T.1]   -0.002231
C(dep)[T.2]    0.004109
female        -0.002682
black          0.001361
lusd          -0.124956
lusd ^ 2       0.113131
dtype: float64 

R2: 0.0001358459598023165 

Standard error: Intercept      0.007516
C(dep)[T.1]    0.021341
C(dep)[T.2]    0.018254
female         0.013603
black          0.020690
lusd           0.015296
lusd ^ 2       0.003627
dtype: float64 

Predictived values: [0.33758858 0.34530457 0.34530457 ... 0.34941367 0.34530457 0.34530457]


In [356]:
new_obs = {'female': [0], 'black': [0], 'dep': [1], 'lusd': [1]}

new_obs = pd.DataFrame(new_obs)
new_obs

female  black  dep  lusd
0       0      0    1     1

In [359]:
y_hat  =  mod.predict(new_obs)
y_hat

0    0.331248
dtype: float64